-- AssetFlow demo data
--
-- Run Database-Initialize.sql first, then run this file in the same database.
-- UUID columns are generated by PostgreSQL. The short business keys in this
-- file are used to resolve relationships and are easier to read in pgAdmin.
--
-- Demo login:
--   Email:    admin@assetflow.test
--   Password: password
--
-- This is development data only. Change or remove the demo credentials before
-- using the database outside a local development environment.

BEGIN;

SET LOCAL search_path TO public;
SET CONSTRAINTS ALL DEFERRED;

DO $$
BEGIN
    IF to_regclass('public.departments') IS NULL THEN
        RAISE EXCEPTION 'AssetFlow schema is missing. Run Database-Initialize.sql first.';
    END IF;
END
$$;

-- ============================================================================
-- Departments and employees
-- ============================================================================

INSERT INTO departments (code, name, description)
VALUES
    ('IT', 'Information Technology', 'Technology operations, infrastructure, and support.'),
    ('FIN', 'Finance', 'Financial planning, reporting, and purchasing oversight.'),
    ('OPS', 'Operations', 'Facilities and day-to-day business operations.')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description;

INSERT INTO employees (
    employee_number, first_name, last_name, email, phone, address,
    job_title, department_id, status, hire_date, created_at, updated_at
)
SELECT employee_number, first_name, last_name, email, phone, address,
       job_title, department.id, status, hire_date, seed.created_at, now()
FROM (
    VALUES
        (
            'EMP-0001', 'Alice', 'Johnson', 'admin@assetflow.test', '+94 11 555 0101',
            '100 Main Street, Colombo', 'IT Director', 'IT', 'ACTIVE'::varchar, DATE '2021-01-11',
            TIMESTAMPTZ '2021-01-11 08:00:00+05:30'
        ),
        (
            'EMP-0002', 'Bob', 'Smith', 'bob.smith@assetflow.test', '+94 11 555 0102',
            '22 Finance Avenue, Colombo', 'Finance Manager', 'FIN', 'ACTIVE'::varchar, DATE '2021-03-15',
            TIMESTAMPTZ '2021-03-15 08:00:00+05:30'
        ),
        (
            'EMP-0003', 'Carol', 'Williams', 'carol.williams@assetflow.test', '+94 11 555 0103',
            '8 Operations Road, Colombo', 'Operations Manager', 'OPS', 'ACTIVE'::varchar, DATE '2022-02-07',
            TIMESTAMPTZ '2022-02-07 08:00:00+05:30'
        ),
        (
            'EMP-0004', 'David', 'Brown', 'david.brown@assetflow.test', '+94 11 555 0104',
            '44 Lake View, Colombo', 'Systems Engineer', 'IT', 'ACTIVE'::varchar, DATE '2023-06-19',
            TIMESTAMPTZ '2023-06-19 08:00:00+05:30'
        ),
        (
            'EMP-0005', 'Eva', 'Davis', 'eva.davis@assetflow.test', '+94 11 555 0105',
            '16 Park Lane, Colombo', 'Financial Analyst', 'FIN', 'ACTIVE'::varchar, DATE '2024-01-08',
            TIMESTAMPTZ '2024-01-08 08:00:00+05:30'
        )
) AS seed(employee_number, first_name, last_name, email, phone, address, job_title, department_code, status, hire_date, created_at)
JOIN departments department ON department.code = seed.department_code
ON CONFLICT (employee_number) DO NOTHING;

UPDATE departments
SET manager_employee_id = employee.id
FROM employees employee
WHERE departments.code = 'IT'
  AND employee.employee_number = 'EMP-0001';

UPDATE departments
SET manager_employee_id = employee.id
FROM employees employee
WHERE departments.code = 'FIN'
  AND employee.employee_number = 'EMP-0002';

UPDATE departments
SET manager_employee_id = employee.id
FROM employees employee
WHERE departments.code = 'OPS'
  AND employee.employee_number = 'EMP-0003';

-- ============================================================================
-- Users, roles, permissions, and mappings
-- ============================================================================

INSERT INTO roles (name, description)
VALUES
    ('SUPER_ADMIN', 'Full access to every AssetFlow module.'),
    ('ADMIN', 'Administrative access to operational modules.'),
    ('DEPARTMENT_HEAD', 'Access to assets and records for a department.'),
    ('USER', 'Basic authenticated workspace access.')
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description;

INSERT INTO permissions (code, description)
VALUES
    ('ASSET_READ', 'View assets and asset details.'),
    ('ASSET_WRITE', 'Create and update assets.'),
    ('EMPLOYEE_READ', 'View employees and departments.'),
    ('EMPLOYEE_WRITE', 'Create and update employees.'),
    ('REPORT_READ', 'View reports and dashboard metrics.'),
    ('SETTINGS_WRITE', 'Manage organization settings.'),
    ('USER_MANAGE', 'Manage application user accounts.'),
    ('MAINTENANCE_WRITE', 'Manage maintenance tickets.'),
    ('PROCUREMENT_WRITE', 'Manage purchase orders and invoices.'),
    ('LICENSE_WRITE', 'Manage software licenses.')
ON CONFLICT (code) DO UPDATE
SET description = EXCLUDED.description;

-- The hash below is BCrypt for the demo password: password
INSERT INTO app_users (
    employee_id, username, password_hash, status, last_login_at,
    created_at, updated_at
)
SELECT employee.id,
       seed.username,
       '$2a$12$WXeKyOJe1RnmcgWWECT6Beqvk9BzoUaMF0k4uZZ7XEQqQfORP1Kda',
       'ACTIVE', NULL, seed.created_at, now()
FROM (
    VALUES
        ('EMP-0001', 'asset.admin', TIMESTAMPTZ '2026-01-02 08:00:00+05:30'),
        ('EMP-0002', 'finance.admin', TIMESTAMPTZ '2026-01-03 08:00:00+05:30')
) AS seed(employee_number, username, created_at)
JOIN employees employee ON employee.employee_number = seed.employee_number
ON CONFLICT (username) DO UPDATE
SET employee_id = EXCLUDED.employee_id,
    password_hash = EXCLUDED.password_hash,
    status = EXCLUDED.status,
    updated_at = now();

INSERT INTO user_roles (user_id, role_id)
SELECT app_user.id, role.id
FROM app_users app_user
JOIN roles role ON role.name = 'SUPER_ADMIN'
WHERE app_user.username = 'asset.admin'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT app_user.id, role.id
FROM app_users app_user
JOIN roles role ON role.name = 'ADMIN'
WHERE app_user.username = 'finance.admin'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM (
    VALUES
        ('SUPER_ADMIN', 'ASSET_READ'),
        ('SUPER_ADMIN', 'ASSET_WRITE'),
        ('SUPER_ADMIN', 'EMPLOYEE_READ'),
        ('SUPER_ADMIN', 'EMPLOYEE_WRITE'),
        ('SUPER_ADMIN', 'REPORT_READ'),
        ('SUPER_ADMIN', 'SETTINGS_WRITE'),
        ('SUPER_ADMIN', 'USER_MANAGE'),
        ('SUPER_ADMIN', 'MAINTENANCE_WRITE'),
        ('SUPER_ADMIN', 'PROCUREMENT_WRITE'),
        ('SUPER_ADMIN', 'LICENSE_WRITE'),
        ('ADMIN', 'ASSET_READ'),
        ('ADMIN', 'ASSET_WRITE'),
        ('ADMIN', 'EMPLOYEE_READ'),
        ('ADMIN', 'EMPLOYEE_WRITE'),
        ('ADMIN', 'REPORT_READ'),
        ('ADMIN', 'MAINTENANCE_WRITE'),
        ('ADMIN', 'PROCUREMENT_WRITE'),
        ('ADMIN', 'LICENSE_WRITE'),
        ('DEPARTMENT_HEAD', 'ASSET_READ'),
        ('DEPARTMENT_HEAD', 'EMPLOYEE_READ'),
        ('DEPARTMENT_HEAD', 'REPORT_READ'),
        ('DEPARTMENT_HEAD', 'MAINTENANCE_WRITE'),
        ('DEPARTMENT_HEAD', 'PROCUREMENT_WRITE'),
        ('USER', 'ASSET_READ'),
        ('USER', 'REPORT_READ')
) AS mapping(role_name, permission_code)
JOIN roles role ON role.name = mapping.role_name
JOIN permissions permission ON permission.code = mapping.permission_code
ON CONFLICT DO NOTHING;

-- ============================================================================
-- Locations, vendors, and asset categories
-- ============================================================================

INSERT INTO locations (
    parent_location_id, code, name, location_type,
    address_line, city, country
)
VALUES
    (NULL, 'HQ', 'AssetFlow Head Office', 'BRANCH', '100 Main Street', 'Colombo', 'Sri Lanka'),
    (NULL, 'NORTH-WH', 'North Distribution Warehouse', 'WAREHOUSE', '12 Industrial Park', 'Colombo', 'Sri Lanka'),
    (NULL, 'FIN-BRANCH', 'Finance Branch Office', 'BRANCH', '22 Finance Avenue', 'Colombo', 'Sri Lanka')
ON CONFLICT (code) DO NOTHING;

UPDATE employees
SET branch_id = CASE
    WHEN department_id = (SELECT id FROM departments WHERE code = 'FIN')
        THEN (SELECT id FROM locations WHERE code = 'FIN-BRANCH')
    ELSE (SELECT id FROM locations WHERE code = 'HQ')
END
WHERE branch_id IS NULL;

INSERT INTO locations (
    parent_location_id, code, name, location_type,
    address_line, city, country
)
VALUES (
    (SELECT id FROM locations WHERE code = 'HQ'),
    'HQ-BLDG', 'Head Office Building', 'BUILDING',
    '100 Main Street', 'Colombo', 'Sri Lanka'
)
ON CONFLICT (code) DO NOTHING;

INSERT INTO locations (
    parent_location_id, code, name, location_type,
    address_line, city, country
)
VALUES (
    (SELECT id FROM locations WHERE code = 'HQ-BLDG'),
    'HQ-2F', 'Technology Floor', 'FLOOR',
    '100 Main Street, Level 2', 'Colombo', 'Sri Lanka'
)
ON CONFLICT (code) DO NOTHING;

INSERT INTO vendors (
    vendor_code, name, contact_name, email, phone, category, address, status
)
VALUES
    ('VEN-TECH', 'TechSource Lanka', 'Nimal Perera', 'sales@techsource.test', '+94 11 555 0201', 'Computing Hardware', '15 Galle Road, Colombo', 'ACTIVE'),
    ('VEN-OFFICE', 'OfficeHub Supplies', 'Malini Fernando', 'orders@officehub.test', '+94 11 555 0202', 'Office Equipment', '80 Union Place, Colombo', 'ACTIVE'),
    ('VEN-NET', 'NetSecure Solutions', 'Ravi Silva', 'support@netsecure.test', '+94 11 555 0203', 'Networking', '9 Park Street, Colombo', 'ACTIVE')
ON CONFLICT (vendor_code) DO NOTHING;

INSERT INTO asset_categories (name, description, is_active)
VALUES
    ('Laptops', 'Portable computers issued to employees.', true),
    ('Monitors', 'External displays and docking displays.', true),
    ('Network Equipment', 'Switches, access points, and network devices.', true),
    ('Office Equipment', 'Furniture and general office equipment.', true),
    ('Software', 'Software and subscription-related assets.', true)
ON CONFLICT (name) DO NOTHING;

-- ============================================================================
-- Purchase orders and items
-- ============================================================================

INSERT INTO purchase_orders (
    po_number, vendor_id, requested_by_employee_id, approved_by_user_id,
    order_date, expected_date, received_date, status, currency,
    subtotal, tax_amount, total_amount, notes
)
VALUES
    (
        'PO-2026-0001',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        (SELECT id FROM employees WHERE employee_number = 'EMP-0001'),
        (SELECT id FROM app_users WHERE username = 'asset.admin'),
        '2026-01-15', '2026-01-22', '2026-01-23', 'RECEIVED', 'USD',
        3525.00, 528.75, 4053.75, 'Initial laptop and monitor refresh.'
    ),
    (
        'PO-2026-0002',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-NET'),
        (SELECT id FROM employees WHERE employee_number = 'EMP-0002'),
        (SELECT id FROM app_users WHERE username = 'finance.admin'),
        '2026-08-01', '2026-09-15', NULL, 'ORDERED', 'USD',
        1200.00, 180.00, 1380.00, 'Network refresh for the warehouse.'
    )
ON CONFLICT (po_number) DO NOTHING;

INSERT INTO purchase_order_items (
    purchase_order_id, category_id, description, quantity, received_quantity, unit_cost
)
SELECT purchase_order.id, category.id, seed.description, seed.quantity, seed.received_quantity, seed.unit_cost
FROM (
    VALUES
        ('PO-2026-0001', 'Laptops', 'Dell Latitude 7440 laptop', 3, 3, 900.00::numeric),
        ('PO-2026-0001', 'Monitors', 'Dell UltraSharp 27-inch monitor', 3, 3, 275.00::numeric),
        ('PO-2026-0002', 'Network Equipment', 'Managed 24-port network switch', 2, 0, 600.00::numeric)
) AS seed(po_number, category_name, description, quantity, received_quantity, unit_cost)
JOIN purchase_orders purchase_order ON purchase_order.po_number = seed.po_number
JOIN asset_categories category ON category.name = seed.category_name
WHERE NOT EXISTS (
    SELECT 1
    FROM purchase_order_items item
    WHERE item.purchase_order_id = purchase_order.id
      AND item.description = seed.description
);

-- ============================================================================
-- Assets and assignments
-- ============================================================================

INSERT INTO assets (
    asset_tag, name, category_id, serial_number, manufacturer, model,
    vendor_id, purchase_order_item_id, purchase_date, purchase_cost, currency,
    location_id, department_id, status, asset_condition, retirement_date,
    disposal_notes, notes
)
VALUES
    (
        'AST-LAP-0001', 'Alice Johnson Laptop',
        (SELECT id FROM asset_categories WHERE name = 'Laptops'), 'TSL-LAT-7440-0001', 'Dell', 'Latitude 7440',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        (SELECT item.id FROM purchase_order_items item JOIN purchase_orders po ON po.id = item.purchase_order_id WHERE po.po_number = 'PO-2026-0001' AND item.description = 'Dell Latitude 7440 laptop'),
        '2026-01-20', 900.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'HQ-2F'),
        (SELECT id FROM departments WHERE code = 'IT'), 'ASSIGNED', 'NEW', NULL, NULL,
        'Primary development laptop.'
    ),
    (
        'AST-LAP-0002', 'Finance Laptop',
        (SELECT id FROM asset_categories WHERE name = 'Laptops'), 'TSL-LAT-7440-0002', 'Dell', 'Latitude 7440',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        (SELECT item.id FROM purchase_order_items item JOIN purchase_orders po ON po.id = item.purchase_order_id WHERE po.po_number = 'PO-2026-0001' AND item.description = 'Dell Latitude 7440 laptop'),
        '2026-01-20', 900.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'NORTH-WH'),
        (SELECT id FROM departments WHERE code = 'FIN'), 'AVAILABLE', 'GOOD', NULL, NULL,
        'Available spare laptop.'
    ),
    (
        'AST-MON-0001', 'Technology Monitor',
        (SELECT id FROM asset_categories WHERE name = 'Monitors'), 'TSL-U2723-0001', 'Dell', 'U2723QE',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        (SELECT item.id FROM purchase_order_items item JOIN purchase_orders po ON po.id = item.purchase_order_id WHERE po.po_number = 'PO-2026-0001' AND item.description = 'Dell UltraSharp 27-inch monitor'),
        '2026-01-20', 275.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'HQ-2F'),
        (SELECT id FROM departments WHERE code = 'IT'), 'AVAILABLE', 'GOOD', NULL, NULL,
        'Shared monitor for the technology team.'
    ),
    (
        'AST-NET-0001', 'Warehouse Network Switch',
        (SELECT id FROM asset_categories WHERE name = 'Network Equipment'), 'NSS-SW-2401', 'Cisco', 'CBS350-24T-4G',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-NET'), NULL,
        '2025-10-01', 850.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'NORTH-WH'),
        (SELECT id FROM departments WHERE code = 'IT'), 'UNDER_MAINTENANCE', 'FAIR', NULL, NULL,
        'Awaiting replacement fan assembly.'
    ),
    (
        'AST-LAP-0003', 'Retired Laptop',
        (SELECT id FROM asset_categories WHERE name = 'Laptops'), 'TSL-LAT-5420-0001', 'Dell', 'Latitude 5420',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'), NULL,
        '2022-04-12', 1100.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'NORTH-WH'),
        (SELECT id FROM departments WHERE code = 'FIN'), 'DISPOSED', 'POOR', '2025-12-20',
        'Recycled after board failure.', 'Historical disposal example.'
    ),
    (
        'AST-OFF-0001', 'Ergonomic Office Chair',
        (SELECT id FROM asset_categories WHERE name = 'Office Equipment'), 'OH-CHAIR-0001', 'ErgoWorks', 'E500',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-OFFICE'), NULL,
        '2025-06-10', 220.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'NORTH-WH'),
        (SELECT id FROM departments WHERE code = 'OPS'), 'AVAILABLE', 'GOOD', NULL, NULL,
        'Warehouse spare.'
    ),
    (
        'AST-NET-0002', 'Warehouse Access Point',
        (SELECT id FROM asset_categories WHERE name = 'Network Equipment'), 'NSS-AP-0002', 'Ubiquiti', 'U6-LR',
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-NET'),
        (SELECT item.id FROM purchase_order_items item JOIN purchase_orders po ON po.id = item.purchase_order_id WHERE po.po_number = 'PO-2026-0002' AND item.description = 'Managed 24-port network switch'),
        '2026-08-05', 600.00, 'LKR',
        (SELECT id FROM locations WHERE code = 'NORTH-WH'),
        (SELECT id FROM departments WHERE code = 'IT'), 'IN_TRANSIT', 'NEW', NULL, NULL,
        'Expected with the warehouse network order.'
    )
ON CONFLICT (asset_tag) DO NOTHING;

INSERT INTO assignments (
    asset_id, employee_id, assigned_by_user_id, assigned_at,
    expected_return_date, returned_at, status, handover_notes
)
SELECT asset.id, employee.id, app_user.id, seed.assigned_at,
       seed.expected_return_date, seed.returned_at, seed.status, seed.handover_notes
FROM (
    VALUES
        ('AST-LAP-0001', 'EMP-0004', 'asset.admin', TIMESTAMPTZ '2026-02-01 09:00:00+05:30', DATE '2027-02-01', NULL::timestamptz, 'ACTIVE', 'Issued for systems engineering work.'),
        ('AST-LAP-0002', 'EMP-0005', 'finance.admin', TIMESTAMPTZ '2025-01-10 09:00:00+05:30', DATE '2025-03-10', TIMESTAMPTZ '2025-03-10 17:00:00+05:30', 'TRANSFERRED', 'Transferred during the finance equipment refresh.'),
        ('AST-LAP-0002', 'EMP-0003', 'asset.admin', TIMESTAMPTZ '2025-03-11 09:00:00+05:30', NULL::date, TIMESTAMPTZ '2025-12-01 17:00:00+05:30', 'RETURNED', 'Returned after the temporary operations assignment.'),
        ('AST-MON-0001', 'EMP-0002', 'asset.admin', TIMESTAMPTZ '2026-03-05 09:00:00+05:30', NULL::date, TIMESTAMPTZ '2026-04-01 17:00:00+05:30', 'RETURNED', 'Returned to shared technology inventory.')
) AS seed(asset_tag, employee_number, username, assigned_at, expected_return_date, returned_at, status, handover_notes)
JOIN assets asset ON asset.asset_tag = seed.asset_tag
JOIN employees employee ON employee.employee_number = seed.employee_number
JOIN app_users app_user ON app_user.username = seed.username
WHERE NOT EXISTS (
    SELECT 1
    FROM assignments existing
    WHERE existing.asset_id = asset.id
      AND existing.employee_id = employee.id
      AND existing.assigned_at = seed.assigned_at
);

-- ============================================================================
-- Warranty policies, claims, and maintenance
-- ============================================================================

INSERT INTO warranty_policies (
    asset_id, vendor_id, policy_number, start_date, end_date,
    coverage, status, is_current
)
SELECT asset.id, vendor.id, seed.policy_number, seed.start_date, seed.end_date,
       seed.coverage, seed.status, seed.is_current
FROM (
    VALUES
        ('AST-LAP-0001', 'VEN-TECH', 'W-TECH-2026-0001', DATE '2026-01-20', DATE '2027-01-20', 'Hardware replacement and onsite support.', 'ACTIVE', true),
        ('AST-NET-0001', 'VEN-NET', 'W-NET-2025-0001', DATE '2025-10-01', DATE '2026-09-05', 'Parts and repair coverage for network hardware.', 'EXPIRING', true),
        ('AST-LAP-0003', 'VEN-TECH', 'W-TECH-2022-0001', DATE '2022-04-12', DATE '2025-12-31', 'Limited hardware warranty.', 'EXPIRED', false)
) AS seed(asset_tag, vendor_code, policy_number, start_date, end_date, coverage, status, is_current)
JOIN assets asset ON asset.asset_tag = seed.asset_tag
JOIN vendors vendor ON vendor.vendor_code = seed.vendor_code
WHERE NOT EXISTS (
    SELECT 1
    FROM warranty_policies existing
    WHERE existing.policy_number = seed.policy_number
);

INSERT INTO warranty_claims (
    warranty_id, assigned_to_user_id, claim_number, opened_at,
    status, description, claimed_amount, provider_reference
)
SELECT warranty.id, app_user.id, seed.claim_number, seed.opened_at,
       seed.status, seed.description, seed.claimed_amount, seed.provider_reference
FROM (
    VALUES
        ('W-NET-2025-0001', 'finance.admin', 'CLM-2026-0001', TIMESTAMPTZ '2026-08-12 10:30:00+05:30', 'SUBMITTED', 'Cooling fan failure reported by the warehouse team.', 350.00::numeric, 'NETSEC-CASE-8842'),
        ('W-TECH-2022-0001', 'asset.admin', 'CLM-2025-0004', TIMESTAMPTZ '2025-12-15 10:30:00+05:30', 'RESOLVED', 'Retired laptop motherboard failure.', 100.00::numeric, 'TECH-CASE-7710')
) AS seed(policy_number, username, claim_number, opened_at, status, description, claimed_amount, provider_reference)
JOIN warranty_policies warranty ON warranty.policy_number = seed.policy_number
JOIN app_users app_user ON app_user.username = seed.username
ON CONFLICT (claim_number) DO NOTHING;

UPDATE warranty_claims
SET resolved_at = '2026-01-05T15:00:00+05:30',
    resolution_notes = 'Asset was approved for recycling and replaced from spare inventory.'
WHERE claim_number = 'CLM-2025-0004';

INSERT INTO maintenance_tickets (
    ticket_number, asset_id, requested_by_employee_id,
    assigned_to_employee_id, vendor_id, issue, description, priority,
    status, opened_at, start_date, due_date, started_at, cost, resolution
)
SELECT seed.ticket_number, asset.id, requester.id, assignee.id, vendor.id,
       seed.issue, seed.description, seed.priority, seed.status,
       seed.opened_at, seed.start_date, seed.due_date, seed.started_at, seed.cost, seed.resolution
FROM (
    VALUES
        ('MT-2026-0001', 'AST-NET-0001', 'EMP-0002', 'EMP-0004', 'VEN-NET', 'Network switch overheating', 'The warehouse switch is reporting repeated temperature alerts.', 'HIGH', 'IN_PROGRESS', TIMESTAMPTZ '2026-08-10 09:15:00+05:30', DATE '2026-08-10', DATE '2026-08-28', TIMESTAMPTZ '2026-08-11 10:00:00+05:30', 150.00::numeric, NULL::text),
        ('MT-2026-0002', 'AST-MON-0001', 'EMP-0001', 'EMP-0004', 'VEN-TECH', 'Monitor flickering', 'Display cable and power board were inspected.', 'MEDIUM', 'COMPLETED', TIMESTAMPTZ '2026-05-01 09:15:00+05:30', DATE '2026-05-01', DATE '2026-05-10', TIMESTAMPTZ '2026-05-02 10:00:00+05:30', 75.00::numeric, 'Power board replaced and monitor returned to inventory.')
) AS seed(ticket_number, asset_tag, requester_number, assignee_number, vendor_code, issue, description, priority, status, opened_at, start_date, due_date, started_at, cost, resolution)
JOIN assets asset ON asset.asset_tag = seed.asset_tag
JOIN employees requester ON requester.employee_number = seed.requester_number
JOIN employees assignee ON assignee.employee_number = seed.assignee_number
JOIN vendors vendor ON vendor.vendor_code = seed.vendor_code
ON CONFLICT (ticket_number) DO NOTHING;

UPDATE maintenance_tickets
SET completed_at = '2026-05-04T16:00:00+05:30'
WHERE ticket_number = 'MT-2026-0002';

-- ============================================================================
-- Software licenses and assignments
-- ============================================================================

INSERT INTO software_licenses (
    software_name, vendor_id, license_type, license_key,
    seat_count, start_date, end_date, purchase_cost, status, notes
)
SELECT seed.software_name, vendor.id, seed.license_type, seed.license_key,
       seed.seat_count, seed.start_date, seed.end_date, seed.purchase_cost,
       seed.status, seed.notes
FROM (
    VALUES
        ('Microsoft 365 E3', 'VEN-TECH', 'SUBSCRIPTION', 'DEMO-M365-2026-0001', 5, DATE '2026-01-01', DATE '2026-12-31', 1200.00::numeric, 'ACTIVE', 'Annual productivity subscription.'),
        ('Adobe Creative Cloud', 'VEN-TECH', 'SUBSCRIPTION', 'DEMO-ADOBE-2026-0001', 2, DATE '2026-04-01', DATE '2027-03-31', 960.00::numeric, 'ACTIVE', 'Design team subscription.'),
        ('Microsoft Visio Standard', 'VEN-TECH', 'PERPETUAL', 'DEMO-VISIO-2024-0001', 1, DATE '2024-01-01', NULL::date, 300.00::numeric, 'ACTIVE', 'Perpetual diagramming license.'),
        ('Network Monitor Trial', 'VEN-NET', 'TRIAL', 'DEMO-NMON-2025-0001', 1, DATE '2025-07-01', DATE '2025-08-31', 0.00::numeric, 'EXPIRED', 'Expired evaluation license.')
) AS seed(software_name, vendor_code, license_type, license_key, seat_count, start_date, end_date, purchase_cost, status, notes)
JOIN vendors vendor ON vendor.vendor_code = seed.vendor_code
WHERE NOT EXISTS (
    SELECT 1
    FROM software_licenses existing
    WHERE existing.license_key = seed.license_key
);

INSERT INTO license_assignments (
    license_id, employee_id, assigned_by_user_id,
    assigned_at, revoked_at, status
)
SELECT license.id, employee.id, app_user.id,
       seed.assigned_at, seed.revoked_at, seed.status
FROM (
    VALUES
        ('DEMO-M365-2026-0001', 'EMP-0004', 'asset.admin', TIMESTAMPTZ '2026-01-05 09:00:00+05:30', NULL::timestamptz, 'ACTIVE'),
        ('DEMO-M365-2026-0001', 'EMP-0005', 'asset.admin', TIMESTAMPTZ '2026-01-05 09:15:00+05:30', NULL::timestamptz, 'ACTIVE'),
        ('DEMO-ADOBE-2026-0001', 'EMP-0001', 'asset.admin', TIMESTAMPTZ '2026-04-02 09:00:00+05:30', NULL::timestamptz, 'ACTIVE'),
        ('DEMO-VISIO-2024-0001', 'EMP-0002', 'finance.admin', TIMESTAMPTZ '2024-02-01 09:00:00+05:30', NULL::timestamptz, 'ACTIVE')
) AS seed(license_key, employee_number, username, assigned_at, revoked_at, status)
JOIN software_licenses license ON license.license_key = seed.license_key
JOIN employees employee ON employee.employee_number = seed.employee_number
JOIN app_users app_user ON app_user.username = seed.username
WHERE NOT EXISTS (
    SELECT 1
    FROM license_assignments existing
    WHERE existing.license_id = license.id
      AND existing.employee_id = employee.id
      AND existing.assigned_at = seed.assigned_at
);

-- ============================================================================
-- Notifications, audit logs, settings, and email templates
-- ============================================================================

INSERT INTO notifications (
    recipient_user_id, notification_type, priority, title, message,
    read_at, created_at
)
SELECT app_user.id, seed.notification_type, seed.priority, seed.title,
       seed.message, seed.read_at, seed.created_at
FROM (
    VALUES
        ('asset.admin', 'MAINTENANCE_DUE', 'HIGH', 'Maintenance ticket due soon', 'Ticket MT-2026-0001 is due on 2026-08-28.', NULL::timestamptz, TIMESTAMPTZ '2026-08-20 08:00:00+05:30'),
        ('asset.admin', 'ASSET_ASSIGNED', 'LOW', 'Asset assigned successfully', 'AST-LAP-0001 is assigned to David Brown.', TIMESTAMPTZ '2026-02-01 12:00:00+05:30', TIMESTAMPTZ '2026-02-01 09:05:00+05:30'),
        ('finance.admin', 'WARRANTY_EXPIRING', 'MEDIUM', 'Warranty is expiring', 'Warranty W-NET-2025-0001 expires on 2026-09-05.', NULL::timestamptz, TIMESTAMPTZ '2026-08-18 08:00:00+05:30')
) AS seed(username, notification_type, priority, title, message, read_at, created_at)
JOIN app_users app_user ON app_user.username = seed.username
WHERE NOT EXISTS (
    SELECT 1
    FROM notifications existing
    WHERE existing.recipient_user_id = app_user.id
      AND existing.title = seed.title
      AND existing.created_at = seed.created_at
);

INSERT INTO audit_logs (
    actor_user_id, entity_type, entity_id, action, old_values, new_values, created_at
)
SELECT app_user.id, seed.entity_type, seed.entity_id, seed.action,
       seed.old_values, seed.new_values, seed.created_at
FROM (
    VALUES
        ('asset.admin', 'APP_USER', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'USER_CREATED', NULL::jsonb, '{"username":"asset.admin","role":"SUPER_ADMIN"}'::jsonb, TIMESTAMPTZ '2026-01-02 08:00:00+05:30'),
        ('asset.admin', 'ASSET', (SELECT id FROM assets WHERE asset_tag = 'AST-LAP-0001'), 'ASSET_CREATED', NULL::jsonb, '{"assetTag":"AST-LAP-0001","status":"ASSIGNED"}'::jsonb, TIMESTAMPTZ '2026-01-20 09:00:00+05:30'),
        ('finance.admin', 'MAINTENANCE_TICKET', (SELECT id FROM maintenance_tickets WHERE ticket_number = 'MT-2026-0001'), 'MAINTENANCE_UPDATED', '{"status":"OPEN"}'::jsonb, '{"status":"IN_PROGRESS","priority":"HIGH"}'::jsonb, TIMESTAMPTZ '2026-08-11 10:00:00+05:30')
) AS seed(username, entity_type, entity_id, action, old_values, new_values, created_at)
JOIN app_users app_user ON app_user.username = seed.username
WHERE NOT EXISTS (
    SELECT 1
    FROM audit_logs existing
    WHERE existing.actor_user_id = app_user.id
      AND existing.action = seed.action
      AND existing.created_at = seed.created_at
);

INSERT INTO system_settings (setting_key, setting_value, updated_by)
VALUES
    ('dashboard.refresh_interval_seconds', '60'::jsonb, (SELECT id FROM app_users WHERE username = 'asset.admin')),
    ('asset.default_currency', '"LKR"'::jsonb, (SELECT id FROM app_users WHERE username = 'asset.admin')),
    ('notifications.email_enabled', 'true'::jsonb, (SELECT id FROM app_users WHERE username = 'asset.admin'))
ON CONFLICT (setting_key) DO UPDATE
SET setting_value = EXCLUDED.setting_value,
    updated_by = EXCLUDED.updated_by,
    updated_at = now();

INSERT INTO organization_settings (
    id, organization_name, industry, primary_contact, currency, timezone,
    branding, notification_settings, updated_by
)
VALUES (
    1, 'AssetFlow Demo Organization', 'Technology Services', 'admin@assetflow.test',
    'LKR', 'Asia/Colombo',
    '{"primaryColor":"#1d4ed8","logoUrl":null}'::jsonb,
    '{"maintenanceAlerts":true,"warrantyAlerts":true,"assignmentAlerts":true}'::jsonb,
    (SELECT id FROM app_users WHERE username = 'asset.admin')
)
ON CONFLICT (id) DO UPDATE
SET organization_name = EXCLUDED.organization_name,
    industry = EXCLUDED.industry,
    primary_contact = EXCLUDED.primary_contact,
    currency = EXCLUDED.currency,
    timezone = EXCLUDED.timezone,
    branding = EXCLUDED.branding,
    notification_settings = EXCLUDED.notification_settings,
    updated_by = EXCLUDED.updated_by,
    updated_at = now();

INSERT INTO notification_preferences (
    user_id, notification_type, in_app_enabled, email_enabled
)
SELECT app_user.id, seed.notification_type, seed.in_app_enabled, seed.email_enabled
FROM (
    VALUES
        ('asset.admin', 'MAINTENANCE_DUE', true, true),
        ('asset.admin', 'WARRANTY_EXPIRING', true, true),
        ('asset.admin', 'ASSET_ASSIGNED', true, false),
        ('finance.admin', 'MAINTENANCE_DUE', true, true),
        ('finance.admin', 'WARRANTY_EXPIRING', true, false)
) AS seed(username, notification_type, in_app_enabled, email_enabled)
JOIN app_users app_user ON app_user.username = seed.username
ON CONFLICT (user_id, notification_type) DO NOTHING;

INSERT INTO email_templates (
    template_key, subject_template, body_template, is_active, updated_by
)
VALUES
    (
        'ASSET_ASSIGNED', 'Asset {{assetTag}} assigned to you',
        'Hello {{employeeName}},\n\nAsset {{assetTag}} - {{assetName}} has been assigned to you.\n\nAssetFlow',
        true, (SELECT id FROM app_users WHERE username = 'asset.admin')
    ),
    (
        'MAINTENANCE_DUE', 'Maintenance ticket {{ticketNumber}} is due soon',
        'Ticket {{ticketNumber}} for {{assetTag}} is due on {{dueDate}}.\n\nAssetFlow',
        true, (SELECT id FROM app_users WHERE username = 'asset.admin')
    ),
    (
        'WARRANTY_EXPIRING', 'Warranty {{policyNumber}} is expiring',
        'Warranty {{policyNumber}} for {{assetTag}} expires on {{endDate}}.\n\nAssetFlow',
        true, (SELECT id FROM app_users WHERE username = 'asset.admin')
    )
ON CONFLICT (template_key) DO NOTHING;

-- ============================================================================
-- Transfers, disposals, valuations, lifecycle events, and department history
-- ============================================================================

INSERT INTO asset_transfers (
    asset_id, previous_assignment_id, new_assignment_id,
    previous_employee_id, new_employee_id, previous_location_id, new_location_id,
    requested_by_user_id, approved_by_user_id, status, reason,
    requested_at, approved_at, transferred_at, notes
)
SELECT asset.id,
       previous_assignment.id,
       new_assignment.id,
       previous_employee.id,
       new_employee.id,
       previous_location.id,
       new_location.id,
       requester.id,
       approver.id,
       'COMPLETED',
       'Temporary finance laptop transferred to operations.',
       TIMESTAMPTZ '2025-03-05 09:00:00+05:30',
       TIMESTAMPTZ '2025-03-06 09:00:00+05:30',
       TIMESTAMPTZ '2025-03-11 09:00:00+05:30',
       'Transfer completed after the operations team handover.'
FROM assets asset
JOIN assignments previous_assignment
  ON previous_assignment.asset_id = asset.id
 AND previous_assignment.assigned_at = TIMESTAMPTZ '2025-01-10 09:00:00+05:30'
JOIN assignments new_assignment
  ON new_assignment.asset_id = asset.id
 AND new_assignment.assigned_at = TIMESTAMPTZ '2025-03-11 09:00:00+05:30'
JOIN employees previous_employee ON previous_employee.employee_number = 'EMP-0005'
JOIN employees new_employee ON new_employee.employee_number = 'EMP-0003'
JOIN locations previous_location ON previous_location.code = 'HQ-2F'
JOIN locations new_location ON new_location.code = 'NORTH-WH'
JOIN app_users requester ON requester.username = 'asset.admin'
JOIN app_users approver ON approver.username = 'asset.admin'
WHERE asset.asset_tag = 'AST-LAP-0002'
  AND NOT EXISTS (
      SELECT 1
      FROM asset_transfers existing
      WHERE existing.asset_id = asset.id
        AND existing.previous_assignment_id = previous_assignment.id
  );

INSERT INTO asset_disposals (
    asset_id, disposal_date, disposal_method, reason, status,
    approved_by_user_id, proceeds, currency, notes
)
VALUES (
    (SELECT id FROM assets WHERE asset_tag = 'AST-LAP-0003'),
    '2025-12-20', 'RECYCLED', 'Motherboard failure and end of useful life.',
    'COMPLETED', (SELECT id FROM app_users WHERE username = 'asset.admin'),
    50.00, 'USD', 'Recycled through the approved electronics disposal partner.'
)
ON CONFLICT (asset_id) DO NOTHING;

INSERT INTO asset_valuations (
    asset_id, valuation_date, book_value, market_value,
    depreciation_amount, valuation_method, currency, created_by_user_id, notes
)
VALUES
    ((SELECT id FROM assets WHERE asset_tag = 'AST-LAP-0001'), '2026-08-01', 720.00, 880.00, 180.00, 'STRAIGHT_LINE', 'USD', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Current monthly valuation.'),
    ((SELECT id FROM assets WHERE asset_tag = 'AST-LAP-0002'), '2026-08-01', 650.00, 700.00, 250.00, 'STRAIGHT_LINE', 'USD', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Current monthly valuation.'),
    ((SELECT id FROM assets WHERE asset_tag = 'AST-NET-0001'), '2026-08-01', 700.00, 650.00, 150.00, 'MARKET_REVIEW', 'USD', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Valuation reduced while under maintenance.'),
    ((SELECT id FROM assets WHERE asset_tag = 'AST-LAP-0003'), '2025-12-20', 0.00, 50.00, 1100.00, 'DISPOSAL_VALUE', 'USD', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Recorded at disposal.'),
    ((SELECT id FROM assets WHERE asset_tag = 'AST-OFF-0001'), '2026-08-01', 180.00, 150.00, 40.00, 'STRAIGHT_LINE', 'USD', (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Current monthly valuation.')
ON CONFLICT (asset_id, valuation_date) DO NOTHING;

INSERT INTO asset_lifecycle_events (
    asset_id, event_type, event_at, actor_user_id,
    from_status, to_status, from_location_id, to_location_id,
    assignment_id, notes, metadata
)
SELECT asset.id, seed.event_type, seed.event_at, app_user.id,
       seed.from_status, seed.to_status, from_location.id, to_location.id,
       assignment.id, seed.notes, seed.metadata
FROM (
    VALUES
        ('AST-LAP-0001', 'PURCHASED', TIMESTAMPTZ '2026-01-20 09:00:00+05:30', 'asset.admin', NULL::varchar, 'AVAILABLE', NULL::varchar, 'HQ-2F', NULL::timestamptz, 'Asset received from TechSource Lanka.', '{"source":"purchase_order","poNumber":"PO-2026-0001"}'::jsonb),
        ('AST-LAP-0001', 'ASSIGNED', TIMESTAMPTZ '2026-02-01 09:00:00+05:30', 'asset.admin', 'AVAILABLE', 'ASSIGNED', 'HQ-2F', 'HQ-2F', TIMESTAMPTZ '2026-02-01 09:00:00+05:30', 'Issued to David Brown.', '{}'::jsonb),
        ('AST-LAP-0002', 'TRANSFERRED', TIMESTAMPTZ '2025-03-11 09:00:00+05:30', 'asset.admin', 'ASSIGNED', 'AVAILABLE', 'HQ-2F', 'NORTH-WH', TIMESTAMPTZ '2025-03-11 09:00:00+05:30', 'Transferred to Operations.', '{}'::jsonb),
        ('AST-NET-0001', 'STATUS_CHANGED', TIMESTAMPTZ '2026-08-10 09:15:00+05:30', 'finance.admin', 'AVAILABLE', 'UNDER_MAINTENANCE', 'NORTH-WH', 'NORTH-WH', NULL::timestamptz, 'Maintenance ticket MT-2026-0001 opened.', '{}'::jsonb),
        ('AST-LAP-0003', 'DISPOSED', TIMESTAMPTZ '2025-12-20 15:00:00+05:30', 'asset.admin', 'RETIRED', 'DISPOSED', 'NORTH-WH', 'NORTH-WH', NULL::timestamptz, 'Asset recycled.', '{}'::jsonb),
        ('AST-NET-0002', 'PURCHASED', TIMESTAMPTZ '2026-08-05 09:00:00+05:30', 'finance.admin', NULL::varchar, 'IN_TRANSIT', NULL::varchar, 'NORTH-WH', NULL::timestamptz, 'Network equipment is in transit to the warehouse.', '{}'::jsonb)
) AS seed(asset_tag, event_type, event_at, username, from_status, to_status, from_location_code, to_location_code, assignment_at, notes, metadata)
JOIN assets asset ON asset.asset_tag = seed.asset_tag
JOIN app_users app_user ON app_user.username = seed.username
LEFT JOIN locations from_location ON from_location.code = seed.from_location_code
LEFT JOIN locations to_location ON to_location.code = seed.to_location_code
LEFT JOIN assignments assignment
  ON assignment.asset_id = asset.id
 AND assignment.assigned_at = seed.assignment_at
WHERE NOT EXISTS (
    SELECT 1
    FROM asset_lifecycle_events existing
    WHERE existing.asset_id = asset.id
      AND existing.event_type = seed.event_type
      AND existing.event_at = seed.event_at
);

INSERT INTO employee_department_history (
    employee_id, previous_department_id, new_department_id,
    changed_by_user_id, effective_from, effective_to, reason, notes
)
SELECT employee.id, previous_department.id, new_department.id,
       app_user.id, seed.effective_from, NULL, seed.reason, seed.notes
FROM (
    VALUES
        ('EMP-0001', NULL::varchar, 'IT', 'asset.admin', DATE '2021-01-11', 'Initial department assignment', 'Joined as the IT department lead.'),
        ('EMP-0002', NULL::varchar, 'FIN', 'asset.admin', DATE '2021-03-15', 'Initial department assignment', 'Joined as Finance Manager.'),
        ('EMP-0003', NULL::varchar, 'OPS', 'asset.admin', DATE '2022-02-07', 'Initial department assignment', 'Joined as Operations Manager.'),
        ('EMP-0004', NULL::varchar, 'IT', 'asset.admin', DATE '2023-06-19', 'Initial department assignment', 'Joined the technology team.'),
        ('EMP-0005', NULL::varchar, 'FIN', 'finance.admin', DATE '2024-01-08', 'Initial department assignment', 'Joined the finance team.')
) AS seed(employee_number, previous_code, new_code, username, effective_from, reason, notes)
JOIN employees employee ON employee.employee_number = seed.employee_number
LEFT JOIN departments previous_department ON previous_department.code = seed.previous_code
JOIN departments new_department ON new_department.code = seed.new_code
JOIN app_users app_user ON app_user.username = seed.username
WHERE NOT EXISTS (
    SELECT 1
    FROM employee_department_history existing
    WHERE existing.employee_id = employee.id
      AND existing.effective_from = seed.effective_from
);

-- ============================================================================
-- Invoices and vendor contracts
-- ============================================================================

INSERT INTO invoices (
    invoice_number, purchase_order_id, vendor_id, invoice_date,
    due_date, paid_date, status, currency, subtotal, tax_amount,
    total_amount, recorded_by_user_id, notes
)
VALUES
    (
        'INV-2026-0001',
        (SELECT id FROM purchase_orders WHERE po_number = 'PO-2026-0001'),
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        '2026-01-24', '2026-02-23', '2026-02-20', 'PAID', 'USD',
        3525.00, 528.75, 4053.75,
        (SELECT id FROM app_users WHERE username = 'asset.admin'), 'Paid by bank transfer.'
    ),
    (
        'INV-2026-0002',
        (SELECT id FROM purchase_orders WHERE po_number = 'PO-2026-0002'),
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-NET'),
        '2026-07-15', '2026-08-15', NULL, 'OVERDUE', 'USD',
        1200.00, 180.00, 1380.00,
        (SELECT id FROM app_users WHERE username = 'finance.admin'), 'Awaiting delivery confirmation.'
    )
ON CONFLICT (invoice_number) DO NOTHING;

INSERT INTO vendor_contracts (
    vendor_id, contract_number, title, start_date, end_date,
    status, contract_value, currency, document_reference, notes
)
VALUES
    (
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-TECH'),
        'CON-TECH-2026-0001', 'Hardware procurement and support agreement',
        '2026-01-01', '2027-12-31', 'ACTIVE', 25000.00, 'USD',
        'contracts/techsource-2026.pdf', 'Preferred hardware supplier.'
    ),
    (
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-OFFICE'),
        'CON-OFFICE-2024-0001', 'Office equipment supply agreement',
        '2024-01-01', '2025-12-31', 'EXPIRED', 12000.00, 'USD',
        'contracts/officehub-2024.pdf', 'Historical office equipment contract.'
    ),
    (
        (SELECT id FROM vendors WHERE vendor_code = 'VEN-NET'),
        'CON-NET-2026-0001', 'Network support and maintenance agreement',
        '2026-08-01', '2027-07-31', 'ACTIVE', 18000.00, 'USD',
        'contracts/netsecure-2026.pdf', 'Includes onsite response support.'
    )
ON CONFLICT (contract_number) DO NOTHING;

COMMIT;

-- Optional verification queries for pgAdmin:
-- SELECT count(*) AS employees FROM employees;
-- SELECT count(*) AS assets FROM assets;
-- SELECT count(*) AS active_assignments FROM assignments WHERE status = 'ACTIVE';
-- SELECT asset_tag, status FROM assets ORDER BY asset_tag;
